### ISSUE TITLE
env.example file location

### ISSUE THREAD

**Issue by hermitagup** [TheLovinator1/discord-reminder-bot#2]
Hi, 
According to project description env.example should be found in extras directory

"Copy .env.example from extras and rename to .env and fill it out."

it is now located inside discord_reminder_bot directory

cheers

**Comment by hermitagup** [comment]
file location updated in commit:  b0214694844bd36ea72aba67ffb8ca09b642d2c2

thank you

**Comment by TheLovinator1** [comment]
I am the one who should thank you!

Don't be afraid to tell me if you need something else :)
